src/objects/Delivery__c.object
<CustomObject>
    <description>Delivery Object that is associated with a customer and could have one or more deliveries</description>
    <fields>
        <fullName>Route__c</fullName>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Delivery</label>
    <nameField>
        <displayFormat>DN-{0000}</displayFormat>
        <label>Delivery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Delivery_Item__c.object
<CustomObject>
    <description>List the delivery items related to a delivery</description>
    <fields>
        <fullName>Delivery_Item_Name__c</fullName>
        <label>Delivery Item Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delivery__c</fullName>
        <label>Delivery</label>
        <referenceTo>Delivery__c</referenceTo>
        <relationshipLabel>Delivery Items</relationshipLabel>
        <relationshipName>Delivery_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Signature_Printed__c</fullName>
        <label>Signee Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Signature__c</fullName>
        <label>Signature</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Delivery Item</label>
    <nameField>
        <displayFormat>DI-{0000}</displayFormat>
        <label>Delivery Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Route__c.object
<CustomObject>
    <description>Route object to display daily route for the drivers</description>
    <fields>
        <fullName>Driver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Route Driver</description>
        <label>Driver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Routes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Route Date</label>
        <type>Date</type>
    </fields>
    <label>Route</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Route No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/testDmController.cls
/* testDmController
 * Kashi @KashifAhmed
 * Description: This class is test class for packaging
*/

@isTest
public class testDmController {
    
    
    static testMethod void deliveryExtension() {
        Route__c rt = new Route__c();
        //insert the route     
        rt.Driver__c =UserInfo.getUserId() ;
        rt.Route_Date__c=System.Today(); 
        insert rt;
        //insert the delivery
        Delivery__c dobj= new Delivery__c();
        
        dobj.Route__c=rt.id;
        insert dobj;
        
        
        Delivery_Item__c  di = new Delivery_Item__c();
        di.Delivery_Item_Name__c    ='test';
        di.Delivery__c=dobj.id;
        insert di;
        
        
        ApexPages.StandardController sc = new ApexPages.StandardController(di);
        deliveryExtension  de =  new deliveryExtension (sc); 
        
        de.SelectedStatus='Open';
        de.deliveryItemId=di.id;
        de.SelectdeliveryItemId=di.id;
        de.routeId=rt.id;
        de.deliveryId=dobj.id;
        de.objAPIName='Delivery_Item__c';
        de.PrintedFieldAPIName='Signature_Printed__c';
        de.SignatureFieldAPIName='Signature__c';
        deliveryExtension.saveAttach('Test Data', di.id); 
        deliveryExtension.saveAttach('Test Data', di.id); 
        deliveryExtension.saveSignature('Delivery_Item__c', di.id,  'printedAPIName',  'printedValue', 'signatureAPIName', 'signatureValue', 37.4224764,22.084);
        de.getRoutes();
        de.getSelectedItem();
        de.getDeliveries();
        de.getDeliveryItems();       
        
        de.redirect();
        
        SSESignatureRegenerate srObj = new  SSESignatureRegenerate();
        
        srObj.objAPIName='Delivery_Item__c';
        srObj.PrintedFieldAPIName='Signature_Printed__c';
        srObj.SignatureFieldAPIName='Signature__c';
        srObj.objId =di.id;
        srObj.getRawSignature();
        
        
        apexpages.currentpage().getparameters().put('id' , di.id);
        displayComments displayCommentsobj = new displayComments();
        
        displayCommentsobj.getFileId();
        
        
       
      
        DeliveryGoogleMapController dgobj= new DeliveryGoogleMapController(sc);
        
         System.assertEquals(dobj.id, di.Delivery__c);
        
      
    }
    
  
    
}