src/objects/Delivery__c.object
<CustomObject>
    <description>Delivery Object that is associated with a customer and could have one or more deliveries</description>
    <fields>
        <fullName>Delivery_Status__c</fullName>
        <label>Delivery Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery with Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <label>Route</label>
        <referenceTo>Route__c</referenceTo>
        <relationshipLabel>Deliveries</relationshipLabel>
        <relationshipName>Deliveries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Delivery</label>
    <nameField>
        <displayFormat>DN-{0000}</displayFormat>
        <label>Delivery Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Delivery_Item__c.object
<CustomObject>
    <description>List the delivery items related to a delivery</description>
    <fields>
        <fullName>Customer_Address__c</fullName>
        <formula>Delivery__r.Customer_Account__r.BillingStreet  &amp;  &apos;, &apos; &amp;  
Delivery__r.Customer_Account__r.BillingCity &amp;  &apos;, &apos; &amp;  
 Delivery__r.Customer_Account__r.BillingState &amp;  &apos;, &apos; &amp;  Delivery__r.Customer_Account__r.BillingPostalCode</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Comments__c</fullName>
        <description>If there are any issues with Delivery, issue reason will be captured here</description>
        <label>Customer Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Delivery_Item_Name__c</fullName>
        <label>Delivery Item Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delivery_Item_Status__c</fullName>
        <label>Delivery Item Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery with Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Delivery__c</fullName>
        <label>Delivery</label>
        <referenceTo>Delivery__c</referenceTo>
        <relationshipLabel>Delivery Items</relationshipLabel>
        <relationshipName>Delivery_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Signature_Date__c</fullName>
        <description>The date and time customer signed the delivery acceptance</description>
        <label>Signature Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Signature_Printed__c</fullName>
        <label>Signee Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Signature__c</fullName>
        <label>Signature</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Delivery Item</label>
    <nameField>
        <displayFormat>DI-{0000}</displayFormat>
        <label>Delivery Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Route__c.object
<CustomObject>
    <description>Route object to display daily route for the drivers</description>
    <fields>
        <fullName>Driver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Route Driver</description>
        <label>Driver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Routes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Route_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Route Date</label>
        <type>Date</type>
    </fields>
    <label>Route</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Route No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/deliveryExtension.cls
/* deliveryExtension
 * Kashi @KashifAhmed
 * Description: This class is the main Delivery Confirmation Page Controller Class
*/

public class deliveryExtension {
    
    
    public string  routeId{get;set;}
    public string  deliveryId{get;set;}
    public string  deliveryItemId{get;set;}
    public string  SelectdeliveryItemId{get;set;}
    public string CurrentUser{get;set;}  
    public string SelectedStatus{get;set;} 
    
    
    public String objAPIName {get; set;}
    public String PrintedFieldAPIName {get; set;}
    public String SignatureFieldAPIName {get; set;}
    
    
    public deliveryExtension(ApexPages.standardController cont) {
        
        currentUser =UserInfo.getUserId();
    }
    
    public PageReference redirect() {
        return new PageReference('/' + SelectdeliveryItemId);   
    }
    
    @remoteAction
    public static void saveAttach(string file, String parentId) {
        
        //signature Already Exist
        list<Attachment> atchLst = new list<Attachment>();
        String filter = '%-'+parentId+'%'; 
        atchLst= [select id,Name,Body from Attachment where Name LIKE :filter limit 1];
        //Check record Already Exist
        if(atchLst.size() > 0){
            
            // Update Signature
            atchLst[0].Body = EncodingUtil.base64Decode(file);  
            
            // Make the update call.
            update atchLst;
            
        }else{
            
            
            Attachment a = new Attachment (ParentId = parentId, Body =EncodingUtil.base64Decode(file) , Name = 'comments-'+parentId+'.png');
            insert a;
        }
    }
    
    @remoteAction
    public static void saveSignature(String objAPIName, String objId, String printedAPIName, String printedValue, String signatureAPIName, String signatureValue, decimal longi, decimal lat) {
        Delivery_Item__c ditm = new Delivery_Item__c();
       
        if(objId !=null & objId!='')
            ditm= [select id, name,Signature_Printed__c,Signature__c,Signature_Date__c, R_D_Coordinates__Latitude__s,R_D_Coordinates__Longitude__s,  Customer_Comments__c from Delivery_Item__c where  id =:objId  limit 1];
        
        ditm.Signature_Printed__c = printedValue;
        ditm.Signature__c = signatureValue;
        ditm.Signature_Date__c= datetime.now();
        ditm.R_D_Coordinates__Longitude__s = longi;
        ditm.R_D_Coordinates__Latitude__s=lat;
        
        update ditm;
    }
    
    
    
    public List<SelectOption> getRoutes() {
        List<SelectOption> routes = new List<SelectOption>();
        list<Route__c> routLst = new list<Route__c>();
        
        routLst = [select id, name from Route__c where  Driver__c =:currentUser and Route_Date__c = TODAY limit 15];
        
        routes.add(new SelectOption('', '--None--'));        
        for (Route__c R: routLst) {
            routes.add(new SelectOption(R.Id, R.Name));
        }
        
        return routes;
    }
    
    public Delivery_Item__c  getSelectedItem(){
        Delivery_Item__c dtc = new Delivery_Item__c(); 
        if(SelectdeliveryItemId !=null & SelectdeliveryItemId !='')
            dtc= [select id, name,Delivery_Item_Status__c,  Delivery_Item_Name__c,Customer_Address__c,Quantity__c,  Customer_Comments__c from Delivery_Item__c where  id =:SelectdeliveryItemId  limit 1];
        
        return dtc;
    }
    
    
    
    
    public List<SelectOption> getDeliveries() {
        List<SelectOption> deliveries = new List<SelectOption>();
        list<Delivery__c> Lst = new list<Delivery__c>();
        
        if(routeId !='' && routeId !=null){
            Lst = [select id, name from Delivery__c where   Route__c =:routeId and Delivery_Status__c !='Delivered' limit 15];
            
            deliveries.add(new SelectOption('', '--None--'));
            for (Delivery__c D: Lst) {
                
                deliveries.add(new SelectOption(D.Id, d.Name));
            }
            
        }   
        
        return deliveries;
    }
    
    public List<SelectOption> getDeliveryItems() {
        List<SelectOption> deliveryItems = new List<SelectOption>();
        list<Delivery_Item__c> Lst = new list<Delivery_Item__c>();
        
        if(deliveryId !='' && deliveryId !=null){
            Lst = [select id, name from Delivery_Item__c where  Delivery__c =:deliveryId and    Delivery_Item_Status__c !='Delivered' limit 15];
            
            deliveryItems.add(new SelectOption('', '--None--'));
            for (Delivery_Item__c D: Lst) {
                
                deliveryItems.add(new SelectOption(D.Id, d.Name));
            }
            
        }   
        
        return deliveryItems;
    }
}